### ISSUE TITLE
Use `lest` for testing.

### ISSUE THREAD

**Issue by yogwoggf** [TAServers/tas-mineclone2#4]
```[tasklist]
### Tasks
- [ ] https://github.com/TAServers/tas-mineclone2/issues/5
- [ ] https://github.com/TAServers/tas-mineclone2/issues/6
- [ ] https://github.com/TAServers/tas-mineclone2/issues/7
- [ ] https://github.com/TAServers/tas-mineclone2/issues/8
```
